const initialTasks = [
  {
    id: "1",
    title: "Grocery Shopping",
    category: "Errands",
    priority: 3,
    dueDate: "2024-04-12",
    assignedTo: ["1", "2"],
  },
  {
    id: "2",
    title: "Pay Electricity Bill",
    category: "Bills",
    priority: 2,
    dueDate: "2024-04-15",
    assignedTo: ["1", "2"],
  },
  {
    id: "3",
    title: "Car Maintenance",
    category: "Maintenance",
    priority: 1,
    dueDate: "2024-04-14",
    assignedTo: ["1", "2"],
  },
  {
    id: "4",
    title: "Parent-Teacher Meeting",
    category: "School",
    priority: 3,
    dueDate: "2024-03-15",
    assignedTo: ["1", "2"],
  },
  {
    id: "5",
    title: "Book Club Meeting",
    category: "Social",
    priority: 1,
    dueDate: "2024-05-20",
    assignedTo: ["1", "2"],
  },
  {
    id: "6",
    title: "Garden Weeding",
    category: "Maintenance",
    priority: 2,
    dueDate: "2024-03-18",
    assignedTo: ["1", "2"],
  },
  {
    id: "7",
    title: "Vet Appointment for Max",
    category: "Pets",
    priority: 3,
    dueDate: "2024-03-22",
    assignedTo: ["1", "2"],
  },
  {
    id: "8",
    title: "Dentist Appointment",
    category: "Health",
    priority: 2,
    dueDate: "2024-03-25",
    assignedTo: ["1", "2"],
  },
  {
    id: "9",
    title: "Replace Smoke Detector Batteries",
    category: "Maintenance",
    priority: 1,
    dueDate: "2024-04-05",
    assignedTo: ["1", "2"],
  },
  {
    id: "10",
    title: "Prepare Guest Room for Visitors",
    category: "Social",
    priority: 2,
    dueDate: "2024-03-30",
    assignedTo: ["1", "2"],
  },
];

export default initialTasks;
